FROM nginx:alpine

COPY ./index.html /usr/share/nginx/html/index.html
COPY ./app.js /usr/share/nginx/html/app.js
COPY ./style.css /usr/share/nginx/html/style.css
COPY ./config.json /usr/share/nginx/html/config.json    # <-- Add this line!

EXPOSE 80
